-- ========================================
-- COMPLETE TIER SYSTEM EVIDENCE AUDIT
-- Verify ACTUAL tier values in use across entire system
-- ========================================

-- 1. What tiers are ACTUALLY being generated by admin?
SELECT 
  'ADMIN CODE GENERATION - HARDCODED VALUES' as evidence,
  'Line 117 of admin_generate_invite_code():' as location,
  'grants_tier = ''premium''' as tier_value,
  'trial_days = 30' as trial_duration,
  'EVERY code generated is identical' as conclusion;

-- 2. What tier values exist in invitation_codes table?
SELECT 
  'INVITATION_CODES TABLE - ACTUAL DATA' as evidence,
  grants_tier,
  COUNT(*) as total_codes,
  SUM(current_uses) as total_uses,
  MAX(created_at) as most_recent
FROM invitation_codes
GROUP BY grants_tier
ORDER BY most_recent DESC;

-- 3. What tier values exist in user_memberships table?
SELECT 
  'USER_MEMBERSHIPS TABLE - ACTUAL DATA' as evidence,
  tier,
  COUNT(*) as total_members,
  AVG(trial_days_total) as avg_trial_days,
  MIN(created_at) as first_signup,
  MAX(created_at) as most_recent_signup
FROM user_memberships
GROUP BY tier
ORDER BY most_recent_signup DESC;

-- 4. Check if ANY other tier values have EVER been used
SELECT 
  'COMPREHENSIVE TIER SCAN' as evidence,
  tier,
  status,
  trial_days_total,
  invitation_code,
  u.email,
  um.created_at
FROM user_memberships um
JOIN auth.users u ON u.id = um.user_id
ORDER BY um.created_at DESC;

-- 5. Verify feature matrix alignment
SELECT 
  'FEATURE MATRIX VERIFICATION' as evidence,
  CASE 
    WHEN EXISTS (
      SELECT 1 FROM user_memberships 
      WHERE tier NOT IN ('premium', 'free', 'anonymous')
    ) THEN '❌ MISMATCH - Unknown tiers in database!'
    ELSE '✅ ALIGNED - Only premium/free tiers exist'
  END as status,
  ARRAY(
    SELECT DISTINCT tier 
    FROM user_memberships 
    ORDER BY tier
  ) as all_tiers_in_use;

-- 6. Check if hi_members table has different tier values
SELECT 
  'HI_MEMBERS TABLE CHECK' as evidence,
  membership_tier,
  COUNT(*) as count
FROM hi_members
GROUP BY membership_tier
ORDER BY count DESC;

-- ========================================
-- CONCLUSION QUERY
-- ========================================
SELECT 
  '📊 FINAL VERDICT' as audit_section,
  (SELECT COUNT(DISTINCT grants_tier) FROM invitation_codes) as distinct_code_tiers,
  (SELECT COUNT(DISTINCT tier) FROM user_memberships) as distinct_member_tiers,
  CASE 
    WHEN (SELECT COUNT(DISTINCT grants_tier) FROM invitation_codes) = 1 
      AND (SELECT COUNT(DISTINCT tier) FROM user_memberships) <= 2
    THEN '✅ SIMPLE SYSTEM - Only premium tier via invite codes'
    ELSE '⚠️ COMPLEX SYSTEM - Multiple tiers in use'
  END as system_complexity;
